/**
 * xudafeng@126.com
 * http://xdf.me/
 */
;(function(global, P) {
  var Util = P.Util;
  var requestAnimationFrame = P.requestAnimationFrame;
  var Vector2d = P.Vector2d;
  var math = P.Math;
  var Sprite = P.Sprite;
  var SourceLoader = P.SourceLoader;
  var IMAGE = '3d.png';
  var doc = document;

  // generated by XSpriteEditor
  var SPRIT_QUERY = [[11,2,140,179,80,60.5,140,179],[188,2,140,179,80,60.5,140,179],[368,2,133,179,83.5,60.5,133,179],[555,3,114,178,93,61,114,178],[726,2,93,179,103.5,60.5,93,179],[35,188,93,179,103.5,60.5,93,179],[200,187,114,180,93,60,114,180],[368,187,133,180,83.5,60,133,180],[542,187,140,179,80,60.5,140,179],[702,188,140,179,80,60.5,140,179]];

  var screen = document.querySelector('#screen');
  var WIDTH = screen.width;
  var HEIGHT = screen.height;
  var ctx = screen.getContext('2d');

  // event
  var Event = {
    on: function(e, type, fn) {
      e.addEventListener(type, fn, false)
    },
    detach: function(e, type, fn) {
      e.removeEventListener(type, fn, false)
    }
  };

  // drag class
  function Drag(cfg) {
    var callback = cfg.callback;
    var container = cfg.container;
    var events = 'ontouchend' in doc
      ? ['touchstart', 'touchmove', 'touchend']
      : ['mousedown', 'mousemove', 'mouseup'];
    function Drag(cfg) {
      Event.on(container, events[0], down);
    }
    function down(e) {
      doc.body.style.cursor = 'e-resize';
      Event.on(doc, events[1], move);
      Event.on(doc, events[2], up);
    }
    function move(e) {
      callback(e);
    }
    function up(e) {
      doc.body.style.cursor = 'default';
      Event.detach(doc, events[1], move);
      Event.detach(doc, events[2], up);
    }
    return new Drag(cfg);
  }

  // init loader
  var loader = new SourceLoader();
  loader.load([{
    id: 'android',
    src: IMAGE
  }]);
  loader.on('success',function(e) {
      var frame = -1;
      var counter = 0;
      new Drag({
        container: global,
        callback: function() {
          if(counter === 5) {
            counter = 0;
            render(frame)
          }
          counter ++;
        }
      });
      function render() {
        if(frame === 9) {
          frame = -1
        }
        frame ++;
        var arr = SPRIT_QUERY[frame];
        ctx.clearRect(0, 0, WIDTH, HEIGHT);
        ctx.drawImage(e.android.image, arr[0], arr[1], arr[2], arr[3], arr[4], arr[5], arr[6], arr[7]);
      }
      render()
  });
})(window, pillow);
